version: '3.9'
services:
  summarize:
    build: .
    environment:
      NODE_ENV: production
      ORG: Soluto
      REDIS_HOST: redis
      REDIS_PORT: '6379'
    volumes:
      - ./data/output:/usr/src/app/data

  redis:
    image: docker.io/bitnami/redis:6.2
    environment:
      - ALLOW_EMPTY_PASSWORD=yes # recommended only for development.
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    volumes:
      - './data/redis:/bitnami/redis/data'
